### ISSUE TITLE
Trusted Cert

### ISSUE THREAD

**Issue by twolsten** [pcfens/puppet-rhn_register#1]
This module works well, but it requires the CA cert to already be pulled down from the Satellite server.  Can you add either a files directory with the option of providing the cert from puppet or an option to pull it down with wget?

**Comment by pcfens** [comment]
Do you install the CA file directly or use the rpm generated by satellite? I wanted to throw some thoughts out before I start on anything to make sure that what I'm thinking addresses the issue without creating new ones.

I can add a new parameter `sslca_source` that contains the URL to the CA, then save the CA to the path in `sslca`. Supporting puppet sources only is certainly easiest, and in this case safer.

Using wget breaks idempotency, or makes it impossible to check for an updated CA certificate. Supporting the RPM using the package type would add complexity, possibly have versioning issues, and not be welcome in many environments since the satellite server delivers it via http by default/necessity.

**Comment by twolsten** [comment]
My thought was to make it available for Puppet to supply the cert.  Have it in the file directory, then do something along the lines of:

file {‘ca-cert':
  ensure => present,
  path   => ‘/usr/share/rhn/',
  owner  => 'root',
  group  => 'root',
  mode   => '0644',
  source => 'puppet:///modules/rhn_register/RHN-ORG-TRUSTED-SSL-CERT',
}
The if / exec command here
File[‘ca-cert'] -> Exec[‘command']

I am not sure if this is the best way, but it was my initial thought.  It would mean that this module would fully automate the satellite registration process, which would be huge.

Let me know what you think.

Thanks,

Tom

**Comment by pcfens** [comment]
Does [this](https://github.com/pcfens/puppet-rhn_register/compare/manage_cert) cover your use case?

I still need to get all of the tests to pass (or drop Ruby 1.8.7) before this gets merged though.

**Comment by twolsten** [comment]
It definitely looks promising, but I am going to test it today and tomorrow to verify.

Thanks for working on this.

Tom

**Comment by pcfens** [comment]
Great - please let me know if it works - I don't have a very good environment for testing this (we use packer to build templates, and they all build with the CA already installed).

If everything works I'll merge it in and make a new release so it can be pulled from the forge.

**Comment by pcfens** [comment]
@twolsten - Have you had a chance to see if this covers your use case?

**Comment by twolsten** [comment]
Phil,

I didn't, only because we had a major roll out for puppet that took up 
most of my time these last few days.  I will be testing it on Monday and 
will let you know then.

Sorry for the delay.

Thanks,

Tom
